/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DatabaseOperationsImpl;
import controller.ExpenseController;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class FinanSTISApp extends javax.swing.JFrame {

    /**
     * Creates new form FinanSTISApp
     */
    
    private CardLayout cardLayout;
    private JPanel mainPanel;
    private boolean isLoggedIn = false;
    private int currentUser = -1;
    private ExpenseController expenseController;
    
    public FinanSTISApp() {
        setTitle("FinanSTIS");
        setSize(600, 750);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        expenseController = new ExpenseController(new DatabaseOperationsImpl());

        initMenuBar();
        initCardLayout();

        setVisible(true);
    }

    private void initMenuBar() {
        setJMenuBar(MenuFactory.createMenuBar(this));
    }

    private void initCardLayout() {
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        // Tambahkan panel ke mainPanel
        mainPanel.add(new LoginPanel(this), "login");
        mainPanel.add(new PemasukanPanel(), "pemasukan");
        mainPanel.add(new PengeluaranPanel(), "pengeluaran");
        mainPanel.add(new TransferPanel(), "transfer");
        mainPanel.add(new TransaksiPanel(), "transaksi");

        add(mainPanel);
    }

    // Set status login
    public void setLoggedIn(boolean loggedIn) {
        this.isLoggedIn = loggedIn;
    }

    // Get status login
    public boolean isLoggedIn() {
        return isLoggedIn;
    }

    // Set ID pengguna saat ini
    public void setCurrentUser(int userId) {
        this.currentUser = userId;
    }

    // Get ID pengguna saat ini
    public int getCurrentUser() {
        return currentUser;
    }

    // Tampilkan view berdasarkan nama view
    public void showView(String viewName) {
        if (viewName.equals("dashboard")) {
            mainPanel.add(new DashboardPanel(expenseController, currentUser), "dashboard");
        }
        cardLayout.show(mainPanel, viewName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FinanSTISApp());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
