/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class FinanSTISApp extends javax.swing.JFrame {

    /**
     * Creates new form FinanSTISApp
     */
    
    private CardLayout cardLayout;
    private JPanel mainPanel;
    private boolean isLoggedIn = false;

    public FinanSTISApp() {
        setTitle("FinanSTIS");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        initMenuBar();
        initCardLayout();

        setVisible(true);
    }

    private void initMenuBar() {
        JMenuBar menuBar = new JMenuBar();

        JMenu menu = new JMenu("Menu");
        menuBar.add(menu);

        JMenuItem loginMenuItem = new JMenuItem("Login");
        loginMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                showView("login");
            }
        });
        menu.add(loginMenuItem);

        JMenuItem dashboardMenuItem = new JMenuItem("Dashboard");
        dashboardMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (isLoggedIn) {
                    showView("dashboard");
                } else {
                    JOptionPane.showMessageDialog(FinanSTISApp.this, "Anda harus login terlebih dahulu!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        menu.add(dashboardMenuItem);

        JMenuItem pemasukanMenuItem = new JMenuItem("Pemasukan");
        pemasukanMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (isLoggedIn) {
                    showView("pemasukan");
                } else {
                    JOptionPane.showMessageDialog(FinanSTISApp.this, "Anda harus login terlebih dahulu!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        menu.add(pemasukanMenuItem);

        JMenuItem pengeluaranMenuItem = new JMenuItem("Pengeluaran");
        pengeluaranMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (isLoggedIn) {
                    showView("pengeluaran");
                } else {
                    JOptionPane.showMessageDialog(FinanSTISApp.this, "Anda harus login terlebih dahulu!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        menu.add(pengeluaranMenuItem);

        JMenuItem transferMenuItem = new JMenuItem("Transfer");
        transferMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (isLoggedIn) {
                    showView("transfer");
                } else {
                    JOptionPane.showMessageDialog(FinanSTISApp.this, "Anda harus login terlebih dahulu!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        menu.add(transferMenuItem);

        JMenuItem transaksiMenuItem = new JMenuItem("Transaksi");
        transaksiMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (isLoggedIn) {
                    showView("transaksi");
                } else {
                    JOptionPane.showMessageDialog(FinanSTISApp.this, "Anda harus login terlebih dahulu!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        menu.add(transaksiMenuItem);

        setJMenuBar(menuBar);
    }

    private void initCardLayout() {
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        // Tambahkan semua panel ke mainPanel
        mainPanel.add(new LoginPanel(this), "login");
        mainPanel.add(new DashboardPanel(), "dashboard");
        mainPanel.add(new PemasukanPanel(), "pemasukan");
        mainPanel.add(new PengeluaranPanel(), "pengeluaran");
        mainPanel.add(new TransferPanel(), "transfer");
        mainPanel.add(new TransaksiPanel(), "transaksi");

        add(mainPanel);
    }

    public void setLoggedIn(boolean loggedIn) {
        this.isLoggedIn = loggedIn;
    }

    public void showView(String viewName) {
        cardLayout.show(mainPanel, viewName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanSTISApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanSTISApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanSTISApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanSTISApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanSTISApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
