/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ExpenseController;
import model.Transaction;

import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class PemasukanPanel extends javax.swing.JPanel {

    private ExpenseController expenseController;
    private FinanSTISApp mainApp;
    private int currentUserId;

    /**
     * Creates new form PemasukanPanel
     */
    public PemasukanPanel(ExpenseController expenseController, FinanSTISApp mainApp, int currentUserId) {
        this.expenseController = expenseController;
        this.mainApp = mainApp;
        this.currentUserId = currentUserId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pemasukanLabel = new javax.swing.JLabel();
        tambahPemasukanPanel = new javax.swing.JPanel();
        deskripsiPemasukanLabel = new javax.swing.JLabel();
        jumlahPemasukanLabel = new javax.swing.JLabel();
        kategoriPemasukanLabel = new javax.swing.JLabel();
        tanggalPemasukanLabel = new javax.swing.JLabel();
        deskripsiPemasukanTextField = new javax.swing.JTextField();
        jumlahPemasukanTextField = new javax.swing.JTextField();
        kategoriPemasukanComboBox = new javax.swing.JComboBox<>();
        PemasukanDateChooser = new com.toedter.calendar.JDateChooser();
        catatPemasukanButton = new javax.swing.JButton();

        pemasukanLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pemasukanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemasukanLabel.setText("Tambah Pemasukan");

        deskripsiPemasukanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deskripsiPemasukanLabel.setText("Deskripsi :");

        jumlahPemasukanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlahPemasukanLabel.setText("Jumlah    :");

        kategoriPemasukanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kategoriPemasukanLabel.setText("Kategori  :");

        tanggalPemasukanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalPemasukanLabel.setText("Tanggal   :");

        deskripsiPemasukanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiPemasukanTextFieldActionPerformed(evt);
            }
        });

        jumlahPemasukanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahPemasukanTextFieldActionPerformed(evt);
            }
        });

        kategoriPemasukanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Bank", "E-Money", "Lainnya" }));

        catatPemasukanButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catatPemasukanButton.setText("CATAT PEMASUKAN!");
        catatPemasukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catatPemasukanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahPemasukanPanelLayout = new javax.swing.GroupLayout(tambahPemasukanPanel);
        tambahPemasukanPanel.setLayout(tambahPemasukanPanelLayout);
        tambahPemasukanPanelLayout.setHorizontalGroup(
            tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPemasukanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPemasukanPanelLayout.createSequentialGroup()
                        .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kategoriPemasukanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahPemasukanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deskripsiPemasukanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deskripsiPemasukanTextField)
                            .addComponent(jumlahPemasukanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addGroup(tambahPemasukanPanelLayout.createSequentialGroup()
                                .addComponent(kategoriPemasukanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(tambahPemasukanPanelLayout.createSequentialGroup()
                        .addComponent(tanggalPemasukanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PemasukanDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(catatPemasukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tambahPemasukanPanelLayout.setVerticalGroup(
            tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPemasukanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskripsiPemasukanLabel)
                    .addComponent(deskripsiPemasukanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahPemasukanLabel)
                    .addComponent(jumlahPemasukanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriPemasukanLabel)
                    .addComponent(kategoriPemasukanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPemasukanLabel)
                    .addComponent(PemasukanDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatPemasukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahPemasukanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pemasukanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pemasukanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahPemasukanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deskripsiPemasukanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiPemasukanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiPemasukanTextFieldActionPerformed

    private void jumlahPemasukanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPemasukanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPemasukanTextFieldActionPerformed

    private void catatPemasukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catatPemasukanButtonActionPerformed
        // TODO add your handling code here:
        // Mendapatkan nilai dari field input
        String deskripsi = deskripsiPemasukanTextField.getText();
        String jumlahStr = jumlahPemasukanTextField.getText();
        String kategori = (String) kategoriPemasukanComboBox.getSelectedItem();
        java.util.Date tanggalUtil = PemasukanDateChooser.getDate();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tanggalUtil);

        if (deskripsi.isEmpty() || jumlahStr.isEmpty() || tanggal == null) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double jumlah;
        try {
            jumlah = Double.parseDouble(jumlahStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get balance ID based on category
        int balanceId = expenseController.getBalanceIdByCategory(currentUserId, kategori);

        Transaction transaksi = new Transaction();
        transaksi.setDescription(deskripsi);
        transaksi.setAmount(jumlah);
        transaksi.setCategory(kategori);
        transaksi.setDate(tanggal);
        transaksi.setUserId(currentUserId);
        transaksi.setType("Pemasukan");
        transaksi.setBalanceId(balanceId);

        boolean success = expenseController.addTransaction(transaksi);
        if (success) {
            boolean updateSuccess = expenseController.updateBalance(transaksi.getBalanceId(), jumlah, "Pemasukan");
            if (updateSuccess) {
                JOptionPane.showMessageDialog(this, "Pemasukan berhasil dicatat!", "Success", JOptionPane.INFORMATION_MESSAGE);
                mainApp.getDashboardPanel().loadData("Hari Ini");
                mainApp.showView("dashboard");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui saldo. Coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mencatat pemasukan. Coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_catatPemasukanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser PemasukanDateChooser;
    private javax.swing.JButton catatPemasukanButton;
    private javax.swing.JLabel deskripsiPemasukanLabel;
    private javax.swing.JTextField deskripsiPemasukanTextField;
    private javax.swing.JLabel jumlahPemasukanLabel;
    private javax.swing.JTextField jumlahPemasukanTextField;
    private javax.swing.JComboBox<String> kategoriPemasukanComboBox;
    private javax.swing.JLabel kategoriPemasukanLabel;
    private javax.swing.JLabel pemasukanLabel;
    private javax.swing.JPanel tambahPemasukanPanel;
    private javax.swing.JLabel tanggalPemasukanLabel;
    // End of variables declaration//GEN-END:variables
}
