/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class PengeluaranPanel extends javax.swing.JPanel {

    /**
     * Creates new form PengeluaranPanel
     */
    public PengeluaranPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengeluaranLabel = new javax.swing.JLabel();
        tambahPengeluaranPanel = new javax.swing.JPanel();
        deskripsiPengeluaranLabel = new javax.swing.JLabel();
        jumlahPengeluaranLabel = new javax.swing.JLabel();
        kategoriPengeluaranLabel = new javax.swing.JLabel();
        tanggalPengeluaranLabel = new javax.swing.JLabel();
        deskripsiPengeluaranTextField = new javax.swing.JTextField();
        jumlahPengeluaranTextField = new javax.swing.JTextField();
        kategoriPeengeluaranComboBox = new javax.swing.JComboBox<>();
        pengeluaranDateChooser = new com.toedter.calendar.JDateChooser();
        catatPengeluaranButton = new javax.swing.JButton();

        pengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pengeluaranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaranLabel.setText("Tambah Pengeluaran");

        deskripsiPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deskripsiPengeluaranLabel.setText("Deskripsi :");

        jumlahPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlahPengeluaranLabel.setText("Jumlah    :");

        kategoriPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kategoriPengeluaranLabel.setText("Kategori  :");

        tanggalPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalPengeluaranLabel.setText("Tanggal   :");

        deskripsiPengeluaranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiPengeluaranTextFieldActionPerformed(evt);
            }
        });

        jumlahPengeluaranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahPengeluaranTextFieldActionPerformed(evt);
            }
        });

        kategoriPeengeluaranComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Tagihan", "Transportasi", "Hiburan", "Kesehatan", "Pendidikan", "Sedekah", "Investasi", "Lain-lain" }));

        catatPengeluaranButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catatPengeluaranButton.setText("CATAT PENGELUARAN!");
        catatPengeluaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catatPengeluaranButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahPengeluaranPanelLayout = new javax.swing.GroupLayout(tambahPengeluaranPanel);
        tambahPengeluaranPanel.setLayout(tambahPengeluaranPanelLayout);
        tambahPengeluaranPanelLayout.setHorizontalGroup(
            tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                        .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kategoriPengeluaranLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahPengeluaranLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deskripsiPengeluaranLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deskripsiPengeluaranTextField)
                            .addComponent(jumlahPengeluaranTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                                .addComponent(kategoriPeengeluaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                        .addComponent(tanggalPengeluaranLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pengeluaranDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(catatPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tambahPengeluaranPanelLayout.setVerticalGroup(
            tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskripsiPengeluaranLabel)
                    .addComponent(deskripsiPengeluaranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahPengeluaranLabel)
                    .addComponent(jumlahPengeluaranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriPengeluaranLabel)
                    .addComponent(kategoriPeengeluaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPengeluaranLabel)
                    .addComponent(pengeluaranDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahPengeluaranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengeluaranLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pengeluaranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahPengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deskripsiPengeluaranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiPengeluaranTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiPengeluaranTextFieldActionPerformed

    private void jumlahPengeluaranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPengeluaranTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPengeluaranTextFieldActionPerformed

    private void catatPengeluaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catatPengeluaranButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catatPengeluaranButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catatPengeluaranButton;
    private javax.swing.JLabel deskripsiPengeluaranLabel;
    private javax.swing.JTextField deskripsiPengeluaranTextField;
    private javax.swing.JLabel jumlahPengeluaranLabel;
    private javax.swing.JTextField jumlahPengeluaranTextField;
    private javax.swing.JComboBox<String> kategoriPeengeluaranComboBox;
    private javax.swing.JLabel kategoriPengeluaranLabel;
    private com.toedter.calendar.JDateChooser pengeluaranDateChooser;
    private javax.swing.JLabel pengeluaranLabel;
    private javax.swing.JPanel tambahPengeluaranPanel;
    private javax.swing.JLabel tanggalPengeluaranLabel;
    // End of variables declaration//GEN-END:variables
}
