/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ExpenseController;
import java.text.SimpleDateFormat;
import model.Transaction;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class PengeluaranPanel extends javax.swing.JPanel {

    private ExpenseController expenseController;
    private FinanSTISApp mainApp;
    private int currentUserId;

    /**
     * Creates new form PengeluaranPanel
     */
    public PengeluaranPanel(ExpenseController expenseController, FinanSTISApp mainApp, int currentUserId) {
        this.expenseController = expenseController;
        this.mainApp = mainApp;
        this.currentUserId = currentUserId;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengeluaranLabel = new javax.swing.JLabel();
        tambahPengeluaranPanel = new javax.swing.JPanel();
        deskripsiPengeluaranLabel = new javax.swing.JLabel();
        jumlahPengeluaranLabel = new javax.swing.JLabel();
        kategoriPengeluaranLabel = new javax.swing.JLabel();
        tanggalPengeluaranLabel = new javax.swing.JLabel();
        deskripsiPengeluaranTextField = new javax.swing.JTextField();
        jumlahPengeluaranTextField = new javax.swing.JTextField();
        kategoriPengeluaranComboBox = new javax.swing.JComboBox<>();
        pengeluaranDateChooser = new com.toedter.calendar.JDateChooser();
        catatPengeluaranButton = new javax.swing.JButton();
        sumberDanaLabel = new javax.swing.JLabel();
        kategoriSumberComboBox = new javax.swing.JComboBox<>();

        pengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pengeluaranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaranLabel.setText("Tambah Pengeluaran");

        deskripsiPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deskripsiPengeluaranLabel.setText("Deskripsi :");

        jumlahPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlahPengeluaranLabel.setText("Jumlah    :");

        kategoriPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kategoriPengeluaranLabel.setText("Kategori  :");

        tanggalPengeluaranLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalPengeluaranLabel.setText("Tanggal   :");

        deskripsiPengeluaranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiPengeluaranTextFieldActionPerformed(evt);
            }
        });

        jumlahPengeluaranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahPengeluaranTextFieldActionPerformed(evt);
            }
        });

        kategoriPengeluaranComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Tagihan", "Transportasi", "Hiburan", "Kesehatan", "Pendidikan", "Sedekah", "Investasi", "Lain-lain" }));

        catatPengeluaranButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catatPengeluaranButton.setText("CATAT PENGELUARAN!");
        catatPengeluaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catatPengeluaranButtonActionPerformed(evt);
            }
        });

        sumberDanaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumberDanaLabel.setText("Sumber  :");

        kategoriSumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Bank", "E-Money", "Lainnya" }));

        javax.swing.GroupLayout tambahPengeluaranPanelLayout = new javax.swing.GroupLayout(tambahPengeluaranPanel);
        tambahPengeluaranPanel.setLayout(tambahPengeluaranPanelLayout);
        tambahPengeluaranPanelLayout.setHorizontalGroup(
            tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                        .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kategoriPengeluaranLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahPengeluaranLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deskripsiPengeluaranLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deskripsiPengeluaranTextField)
                            .addComponent(jumlahPengeluaranTextField)
                            .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                                .addComponent(kategoriPengeluaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sumberDanaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)
                                .addComponent(kategoriSumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                        .addComponent(tanggalPengeluaranLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pengeluaranDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(catatPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tambahPengeluaranPanelLayout.setVerticalGroup(
            tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPengeluaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskripsiPengeluaranLabel)
                    .addComponent(deskripsiPengeluaranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahPengeluaranLabel)
                    .addComponent(jumlahPengeluaranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriPengeluaranLabel)
                    .addComponent(kategoriPengeluaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumberDanaLabel)
                    .addComponent(kategoriSumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPengeluaranLabel)
                    .addComponent(pengeluaranDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahPengeluaranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengeluaranLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pengeluaranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahPengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deskripsiPengeluaranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiPengeluaranTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiPengeluaranTextFieldActionPerformed

    private void jumlahPengeluaranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPengeluaranTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPengeluaranTextFieldActionPerformed

    private void catatPengeluaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catatPengeluaranButtonActionPerformed
        // TODO add your handling code here:
        // Mendapatkan nilai dari field input
        String deskripsi = deskripsiPengeluaranTextField.getText();
        String jumlahStr = jumlahPengeluaranTextField.getText();
        String kategoriPengeluaran = (String) kategoriPengeluaranComboBox.getSelectedItem();
        String kategoriSumber = (String) kategoriSumberComboBox.getSelectedItem();
        java.util.Date tanggalUtil = pengeluaranDateChooser.getDate();

        // Format tanggal ke string
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tanggalUtil);

        // Validasi input
        if (deskripsi.isEmpty() || jumlahStr.isEmpty() || tanggal == null) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double jumlah;
        try {
            jumlah = Double.parseDouble(jumlahStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get balance ID based on sumber dana (kategori sumber saldo)
        int balanceIdSumber = expenseController.getBalanceIdByCategory(currentUserId, kategoriSumber);
        System.out.println("Balance ID untuk kategori sumber " + kategoriSumber + ": " + balanceIdSumber);

        // Buat transaksi baru
        Transaction transaksi = new Transaction();
        transaksi.setDescription(deskripsi);
        transaksi.setAmount(jumlah);
        transaksi.setCategory(kategoriPengeluaran);
        transaksi.setDate(tanggal);
        transaksi.setUserId(currentUserId);
        transaksi.setType("Pengeluaran");
        transaksi.setBalanceId(balanceIdSumber); // Use the balance ID from sumber dana

        // Simpan transaksi ke database
        boolean success = expenseController.addTransaction(transaksi);
        if (success) {
            boolean updateSuccess = expenseController.updateBalance(transaksi.getBalanceId(), jumlah, "Pengeluaran");
            if (updateSuccess) {
                JOptionPane.showMessageDialog(this, "Pengeluaran berhasil dicatat!", "Success", JOptionPane.INFORMATION_MESSAGE);
                mainApp.getDashboardPanel().loadData("Hari Ini");
                mainApp.showView("dashboard");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui saldo. Coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mencatat pengeluaran. Coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_catatPengeluaranButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catatPengeluaranButton;
    private javax.swing.JLabel deskripsiPengeluaranLabel;
    private javax.swing.JTextField deskripsiPengeluaranTextField;
    private javax.swing.JLabel jumlahPengeluaranLabel;
    private javax.swing.JTextField jumlahPengeluaranTextField;
    private javax.swing.JComboBox<String> kategoriPengeluaranComboBox;
    private javax.swing.JLabel kategoriPengeluaranLabel;
    private javax.swing.JComboBox<String> kategoriSumberComboBox;
    private com.toedter.calendar.JDateChooser pengeluaranDateChooser;
    private javax.swing.JLabel pengeluaranLabel;
    private javax.swing.JLabel sumberDanaLabel;
    private javax.swing.JPanel tambahPengeluaranPanel;
    private javax.swing.JLabel tanggalPengeluaranLabel;
    // End of variables declaration//GEN-END:variables
}
