/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ExpenseController;
import model.Transaction;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class TransaksiPanel extends javax.swing.JPanel {

    private ExpenseController expenseController;
    private int currentUserId;

    /**
     * Creates new form TransaksiPanel
     */
    public TransaksiPanel(ExpenseController expenseController, int currentUserId) {
        this.expenseController = expenseController;
        this.currentUserId = currentUserId;
        initComponents();
        loadTransactionData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        riwayatTransaksiLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();

        riwayatTransaksiLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        riwayatTransaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riwayatTransaksiLabel.setText("RIWAYAT TRANSAKSI");

        transaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipe", "Tanggal", "Kategori Pengeluaran", "Jumlah", "Deskripsi", "Sumber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transaksiTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riwayatTransaksiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(riwayatTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadTransactionData() {
    List<Transaction> transactions = expenseController.getAllTransactions(currentUserId);

    // Urutkan transaksi berdasarkan tanggal dari terbaru ke terlama
    transactions.sort((t1, t2) -> {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date1 = sdf.parse(t1.getDate());
            Date date2 = sdf.parse(t2.getDate());
            return date2.compareTo(date1);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return 0;
    });

    // Buat model tabel dan setel ke transaksiTable
    DefaultTableModel model = (DefaultTableModel) transaksiTable.getModel();
    model.setRowCount(0); // Hapus baris yang ada

    for (Transaction transaction : transactions) {
        Object[] row = {
            transaction.getType(),
            transaction.getDate(),
            transaction.getCategory(),
            transaction.getAmount(),
            transaction.getDescription(),
            expenseController.getCategoryByBalanceId(transaction.getBalanceId())
        };
        model.addRow(row);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel riwayatTransaksiLabel;
    private javax.swing.JTable transaksiTable;
    // End of variables declaration//GEN-END:variables
}
