/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Yedija Lewi Suryadi (222212921 - 2KS1 - Politeknik Statistika STIS 2024)
 */
public class TransferPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransferPanel
     */
    public TransferPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferSaldoLabel = new javax.swing.JLabel();
        transferSaldoPanel = new javax.swing.JPanel();
        tanggalTransferSaldoLabel = new javax.swing.JLabel();
        transferSaldoDateChooser = new com.toedter.calendar.JDateChooser();
        catatTransferSaldoButton = new javax.swing.JButton();
        kategoriTransferSaldoDariComboBox = new javax.swing.JComboBox<>();
        transferSaldoDariLabel = new javax.swing.JLabel();
        transferSaldoKeLabel = new javax.swing.JLabel();
        kategoriTransferSaldoKeComboBox = new javax.swing.JComboBox<>();
        biayaAdminLabel = new javax.swing.JLabel();
        biayaAdminTextField = new javax.swing.JTextField();

        transferSaldoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transferSaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferSaldoLabel.setText("Transfer Saldo");

        tanggalTransferSaldoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalTransferSaldoLabel.setText("Tanggal   :");

        catatTransferSaldoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catatTransferSaldoButton.setText("CATAT TRANSFER SALDO");
        catatTransferSaldoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catatTransferSaldoButtonActionPerformed(evt);
            }
        });

        kategoriTransferSaldoDariComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Bank", "E-Money", "Lainnya" }));

        transferSaldoDariLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferSaldoDariLabel.setText("Dari:");

        transferSaldoKeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferSaldoKeLabel.setText("Ke:");

        kategoriTransferSaldoKeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Bank", "E-Money", "Lainnya" }));

        biayaAdminLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        biayaAdminLabel.setText("Biaya Admin:");

        biayaAdminTextField.setText("0");
        biayaAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaAdminTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferSaldoPanelLayout = new javax.swing.GroupLayout(transferSaldoPanel);
        transferSaldoPanel.setLayout(transferSaldoPanelLayout);
        transferSaldoPanelLayout.setHorizontalGroup(
            transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferSaldoPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(catatTransferSaldoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(transferSaldoPanelLayout.createSequentialGroup()
                        .addGroup(transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transferSaldoDariLabel)
                            .addComponent(transferSaldoKeLabel)
                            .addComponent(kategoriTransferSaldoDariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategoriTransferSaldoKeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalTransferSaldoLabel)
                            .addGroup(transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(biayaAdminTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(biayaAdminLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(transferSaldoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        transferSaldoPanelLayout.setVerticalGroup(
            transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferSaldoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(transferSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transferSaldoPanelLayout.createSequentialGroup()
                        .addComponent(transferSaldoDariLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategoriTransferSaldoDariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferSaldoKeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategoriTransferSaldoKeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transferSaldoPanelLayout.createSequentialGroup()
                        .addComponent(tanggalTransferSaldoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferSaldoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(biayaAdminLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(biayaAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatTransferSaldoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transferSaldoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferSaldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(transferSaldoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferSaldoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void catatTransferSaldoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catatTransferSaldoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catatTransferSaldoButtonActionPerformed

    private void biayaAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayaAdminTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biayaAdminLabel;
    private javax.swing.JTextField biayaAdminTextField;
    private javax.swing.JButton catatTransferSaldoButton;
    private javax.swing.JComboBox<String> kategoriTransferSaldoDariComboBox;
    private javax.swing.JComboBox<String> kategoriTransferSaldoKeComboBox;
    private javax.swing.JLabel tanggalTransferSaldoLabel;
    private javax.swing.JLabel transferSaldoDariLabel;
    private com.toedter.calendar.JDateChooser transferSaldoDateChooser;
    private javax.swing.JLabel transferSaldoKeLabel;
    private javax.swing.JLabel transferSaldoLabel;
    private javax.swing.JPanel transferSaldoPanel;
    // End of variables declaration//GEN-END:variables
}
